name: example-environment
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - notebook
  - numpy
  - scipy
  - pyproj
  - matplotlib
  - netCDF4
  - h5py
  - gdal
  - pip:
     - git+https://github.com/suzanne64/ATL11.git
     - git+https://github.com/tsutterley/pyTMD.git
